# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-ChartHist
version:      0.03
version_from: lib/Finance/ChartHist.pm
installdirs:  site
requires:
    Date::Simple:                  0
    Finance::QuoteHist:            1.09
    GD::Graph:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
